const fs = require('fs');
const path = require('path');

const read = (relativePath) => fs.readFileSync(path.join(__dirname, '..', '..', relativePath), 'utf8');

describe('billing dashboard controls contract', () => {
    test('localizes only the billing metadata required by sidebar/editor flows', () => {
        const classAssets = read('includes/class-assets.php');
        expect(classAssets).toContain("'adminDashboardUrl' => esc_url_raw(admin_url('admin.php?page=aivi-settings'))");
        expect(classAssets).toContain("'apiEndpoints' => AIVI_API_ENDPOINTS");
        expect(classAssets).toContain("'billingProvider' => AIVI_BILLING_PROVIDER");
        expect(classAssets).toContain("'billingReady' => (bool) AIVI_BILLING_READY");
        expect(classAssets).not.toContain("'billingCatalog' => Admin_Settings::get_public_billing_catalog()");
        expect(classAssets).not.toContain('PAYPAL_CLIENT_SECRET');
        expect(classAssets).not.toContain('PAYPAL_WEBHOOK_ID');
    });

    test('admin dashboard exposes hosted billing actions without raw provider secrets', () => {
        const adminSettings = read('includes/class-admin-settings.php');
        expect(adminSettings).toContain('public static function get_public_billing_catalog()');
        expect(adminSettings).toContain("id=\"aivi-billing-plans\"");
        expect(adminSettings).toContain("id=\"aivi-billing-topups\"");
        expect(adminSettings).toContain("id=\"aivi-billing-status\"");
        expect(adminSettings).toContain("id=\"aivi-billing-result\"");
        expect(adminSettings).toContain("data-account-action=\"start_trial\"");
        expect(adminSettings).toContain('data-account-connect-submit');
        expect(adminSettings).toContain('Connect with token');
        expect(adminSettings).toContain('Growth and Pro multi-site connections currently use an operator-issued connection token.');
        expect(adminSettings).toContain('Request connection token');
        expect(adminSettings).toContain('Latest connection token');
        expect(adminSettings).toContain('Copy token');
        expect(adminSettings).toContain('Connected sites');
        expect(adminSettings).toContain('Disconnect this site');
        expect(adminSettings).toContain("data-connection-action=\"disconnect\"");
        expect(adminSettings).toContain("data-billing-action=\"<?php echo esc_attr( $plan_change_requires_guard ? 'plan_change_info' : 'subscribe' ); ?>\"");
        expect(adminSettings).toContain("data-billing-action=\"topup\" data-topup-pack-code=\"<?php echo esc_attr( $topup_code ); ?>\"");
        expect(adminSettings).toContain('Connect this site to an AiVI account before starting a plan or adding top-up credits.');
        expect(adminSettings).toContain('Start free trial');
        expect(adminSettings).toContain('data-aivi-trial-contact-email="true"');
        expect(adminSettings).toContain('Contact email (optional)');
        expect(adminSettings).toContain('Optional. Add one if you want AiVI billing and support follow-ups tied to a specific address for this site.');
        expect(adminSettings).not.toContain('data-aivi-trial-email-modal="true"');
        expect(adminSettings).not.toContain('Continue to free trial');
        expect(adminSettings).not.toContain('Add the best email for account updates');
        expect(adminSettings).toContain('supportCenter: <?php echo wp_json_encode( $support_center_config ); ?>');
        expect(adminSettings).toContain('data-aivi-support-composer="true"');
        expect(adminSettings).toContain('id="aivi-support-message-compose"');
        expect(adminSettings).toContain('id="aivi-support-submit"');
        expect(adminSettings).toContain('var supportCategoryConfig = <?php echo wp_json_encode( $support_category_configs ); ?>;');
        expect(adminSettings).toContain('function ensureZohoDeskAsapReady(supportConfig)');
        expect(adminSettings).toContain("invoke('routeTo', {");
        expect(adminSettings).toContain("ticket.form.prefillValues");
        expect(adminSettings).toContain('id="aivi-support-result"');
        expect(adminSettings).toContain('public static function get_preferred_contact_email()');
        expect(adminSettings).not.toContain("return sanitize_email( (string) get_bloginfo( 'admin_email' ) );");
        expect(adminSettings).toContain('X-AIVI-Admin-Email');
        expect(adminSettings).toContain('This site must be linked to AiVI before analysis starts.');
        expect(adminSettings).toContain('Disconnecting here removes only this site binding.');
        expect(adminSettings).toContain('private static function can_show_dashboard_topups( $dashboard_state, $account_state )');
        expect(adminSettings).toContain("if ( strtolower( $value ) === 'success_partial' )");
        expect(adminSettings).toContain("case 'paused':");
        expect(adminSettings).toMatch(/case 'error':\s+case 'payment_failed':/);
        expect(adminSettings).toContain("return in_array( $plan_code, AIVI_PLAN_CODES, true ) && 'active' === $status;");
        expect(adminSettings).toContain("<?php if ( $can_show_topups ) : ?>");
        expect(adminSettings).toContain('PayPal approval');
        expect(adminSettings).toContain('Awaiting activation');
        expect(adminSettings).toContain("case 'subscription_retry_ready':");
        expect(adminSettings).toContain('Plan changes stay aligned with your billing cycle');
        expect(adminSettings).toContain("$plan_change_requires_guard ? 'plan_change_info' : 'subscribe'");
        expect(adminSettings).toContain('Upgrade plan');
        expect(adminSettings).toContain('Downgrade at renewal');
        expect(adminSettings).toContain('Open plans tab');
        expect(adminSettings).toContain("$billing_plan_grid_href = add_query_arg( 'aivi_tab', 'billing', $settings_page_base_url ) . '#aivi-settings-plan-grid';");
        expect(adminSettings).toContain('<a class="button button-primary" href="<?php echo esc_url( $billing_plan_grid_href ); ?>" data-aivi-settings-tab-link="billing">');
        expect(adminSettings).toContain('function scrollToSettingsTarget(hash) {');
        expect(adminSettings).toContain("if (targetUrl.hash && targetTab !== 'documentation') {");
        expect(adminSettings).toContain('scrollToSettingsTarget(targetUrl.hash);');
        expect(adminSettings).toContain('Top-ups add extra capacity to an active paid subscription.');
        expect(adminSettings).toContain('var inlineAiviSettingsConfig = {');
        expect(adminSettings).toContain('function getSettingsApiConfig() {');
        expect(adminSettings).toContain('restBase: <?php echo wp_json_encode( esc_url_raw( rest_url( \'aivi/v1\' ) ) ); ?>');
        expect(adminSettings).toContain('apiEndpoints: <?php echo wp_json_encode( AIVI_API_ENDPOINTS ); ?>');
        expect(adminSettings).toContain('function resolveConnectionEndpoint(action) {');
        expect(adminSettings).toContain("if (action === 'connect') return endpoints.account_connect || '';");
        expect(adminSettings).toContain("if (action === 'disconnect') return endpoints.account_disconnect || '';");
        expect(adminSettings).toContain('notify_backend: true');
        expect(adminSettings).toContain('window.open(approvalUrl,');
        expect(adminSettings).not.toContain('PAYPAL_CLIENT_SECRET');
        expect(adminSettings).not.toContain('providerSubscriptionId');
        expect(adminSettings).not.toContain('providerOrderId');

        const billingActionBlockStart = adminSettings.indexOf("$('.aivi-billing-action').on('click', function() {");
        const billingActionBlockEnd = adminSettings.indexOf("$.ajax({", billingActionBlockStart);
        const billingActionBlock = adminSettings.slice(billingActionBlockStart, billingActionBlockEnd);
        expect(billingActionBlock.indexOf("if (action === 'plan_change_info') {")).toBeGreaterThan(-1);
        expect(billingActionBlock.indexOf('if (!restBase || !endpoint || !nonce) {')).toBeGreaterThan(-1);
        expect(billingActionBlock.indexOf("if (action === 'plan_change_info') {")).toBeLessThan(billingActionBlock.indexOf('if (!restBase || !endpoint || !nonce) {'));
    });
});
